### ISSUE TITLE
MPV with Angle : doesn't build for me (both 32/64 bits are affected)

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#220]
MPV detects Angle correctly, but when trying to link the mpv.exe I get the following error:
```
[228/234] Compiling [32mstream/stream_file.c[0m
[229/234] Compiling [32mplayer/misc.c[0m
[230/234] Compiling [32maudio/decode/dec_audio.c[0m
[231/234] Linking [33mbuild/mpv.com[0m
[32m+ install /local64/bin-video/mpv.com (from build/mpv.com)[0m
[233/234] Linking [33mbuild/mpv.exe[0m
K:/Mingw642/local64/lib\libGLESv2.a(global_state.o):global_state.cpp:(.text+0x100): multiple definition of `DllMain'

K:/Mingw642/msys64/mingw64/lib\libcrypto.a(cryptlib.o):(.text+0xab0): first defined here

collect2.exe: error: ld returned 1 exit status
```
Any ideas ?

**Comment by wiiaboo** [comment]
Seems like some problems with OpenSSL. I just tested with SChannel and GnuTLS.

**Comment by wiiaboo** [comment]
Can you try adding `-Wl,--allow-multiple-definition` to LDFLAGS in mpv and see if that fixes it? I'm kinda busy atm.

**Comment by pat357** [comment]
Yup, if I use gnutls, I got a similar error with libutv.
Now it works with GNUTLS if I remove LIBUTV from the options in ffmpeg.

**Comment by wiiaboo** [comment]
Heh, weird. Can you paste your ffmpeg_options.txt so I can test it later?

**Comment by pat357** [comment]
BTW, how did you enable SChannel with gnutls ?
I always use --enable-gnutls --enable-gmp  together.
I suppose using  --enable-gnutls only will add SChannel automaticly, just like for openssl ?

My ffmpeg_options.txt:
```
--disable-decoder=dca
--disable-encoder=vorbis
# --disable-w32threads
# --enable-avisynth
--enable-avresample
--enable-decklink
--enable-fontconfig
--enable-frei0r
 --enable-gmp
 --enable-gnutls
--enable-libass
--enable-libbluray
--enable-libbs2b
--enable-libcaca
--enable-libcdio
--enable-libdcadec
--enable-libfdk-aac
--enable-libfreetype
--enable-libfribidi
--enable-libgme
--enable-libgsm
--enable-libilbc
--enable-libkvazaar
--enable-libmfx
--enable-libmodplug
--enable-libmp3lame
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libopenjpeg
--enable-libopus
--enable-librubberband
--enable-librtmp
--enable-libschroedinger
--enable-libsnappy
--enable-libsoxr
--enable-libspeex
--enable-libtesseract
--enable-libtheora
--enable-libtwolame
# --enable-libutvideo
--enable-libvidstab
# --enable-libvo-aacenc
--enable-libvo-amrwbenc
--enable-libvorbis
--enable-libvpx
--enable-libwavpack
--enable-libwebp
--enable-libx264
--enable-libx265
--enable-libxavs
--enable-libxvid
--enable-libzimg
--enable-libzvbi
--enable-nonfree
--enable-nvenc
--enable-opencl
--enable-opengl
# --enable-openssl
# --disable-doc

**Comment by wiiaboo** [comment]
I mean the .ini, sorry, but the ffmpeg_options is useful too.

I don't have SChannel with GnuTLS, just SChannel. It handles https and enables rtmp(t)e so neither OpenSSL nor GnuTLS are needed for Windows.

**Comment by pat357** [comment]
I just tested again with gnutls and libutv enabled as options.
With the extra LDFLAG  "-Wl,--allow-multiple-definition", mpv builds ok !
Will test this flag with openssl now and let you know how it works out.

**Comment by pat357** [comment]
I suppose you meant my media-autobuild_suite.ini ?
```
[compiler list]
msys2Arch=2
arch=1
license2=1
vpx=1
x264=4
xpcomp=2
x265=1
other265=2
flac=1
fdkaac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
rtmpdump=1
mplayer=2
mpv=1
cores=7
deleteSource=2
strip=2
pack=2

**Comment by pat357** [comment]
The extra " LDFLAG  "-Wl,--allow-multiple-definition" solved both my problems I had with MPV/Angle the ffmpeg optional libs LibUTV and OPENSSL. 
If this flag brings no new problems when using MPV, I'd recommend to add it as default to the compiling options from MPV.

Also, add cpuCount to the compilation from Angle to speed it up a bit.
You may close this issue as far as I'm concerned.

**Comment by wiiaboo** [comment]
Last commits should fix it without having to use the flag which might mask other errors.
Haven't tested with a full build yet, just with mine.

**Comment by wiiaboo** [comment]
I noticed you managed to compile vapoursynth statically with mpv. Mind sharing how?

**Comment by wiiaboo** [comment]
@pat357  I noticed you managed to compile vapoursynth statically with mpv. Mind sharing how?

**Comment by wiiaboo** [comment]
@pat357 ping

**Comment by pat357** [comment]
```
Have you installed Vapoursynth ?
If yes, then you should find the needed files under the sdk directory from where you installed vapoursynth.
For 32bit is this for example:

c:\Program Files (x86)\VapourSynth\sdk\lib32\

You just need to copy the files from /lib32 to your /local32/lib and from /lib64 to /local64/lib.
I still don't know how the files should be called, so I have several times the same file with a different name in my /local32/lib.

Then the tricky part : the pc files in local{32,64} 
I''ll add the 2 files that are working for me :
The pc files go to /local{32,64/lib/pkgconfig

The correct name from the .lib files can probably be found by looking in the ,pc files, but I couldn't do it.

This is a short explanation of how to install vapoursynth for MPV.
Notice that the files are extremely small : they just allow MPV to talk to vapoursynth.

What you asked for (statically build with MPV) is virtually impossible : you would need to include the whole vapoursynth + all the plugins + python to get a real statically build).

If you have still questions, just ask them.
In case you know how the lib files should be called by looking in the PC files, please let me know, so that I can finally remove the unneeded files from my local32/lib dir.

BTW vapoursynth is great tool, and I really love it.
The native 64bit version is really what avisynth users were missing. Only 2-4 GB available , even when your PC has 32GB is ridiculous.
In mean time there is also Avisynth+, with a 64 bit version, but I haven't used it much.

**Comment by wiiaboo** [comment]
Ah, so it's not a proper static build like I thought. Yeah, shared I've managed already, but that needs both shared vapoursynth.dll and libpython.dll to work, like Angle did. Static compilation would need static python, yes. Final mpv would be huge.
Thanks anyway.

**Comment by pat357** [comment]
So you know the names from the libs that are used ?
Would you care to share these names ?

**Comment by wiiaboo** [comment]
I assume it's vapoursynth.lib and vapoursynth-script.lib.
https://github.com/vapoursynth/vapoursynth/blob/master/pc/vapoursynth.pc.in
https://github.com/vapoursynth/vapoursynth/blob/master/pc/vapoursynth-script.pc.in

**Comment by pat357** [comment]
I still don't understand why these are not included in the VS installer as an option to install.
Can you post your vapoursynth.pc and  vapoursynth-script.pc ?

**Comment by wiiaboo** [comment]
Because pkg-config files are used for *nix builds, not Visual Studio stuff.

vapoursynth.pc
```makefile
prefix=/local64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/vapoursynth

Name: vapoursynth
Description: A frameserver for the 21st century
Version: 30

Requires.private: zimg
Libs: -L${libdir} -lvapoursynth
Libs.private: -LC:/builds/ab/local64/lib -lzimg -lstdc++ 
Cflags: -I${includedir}
```

vapoursynth-script.pc
```makefile
prefix=/local64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/vapoursynth

Name: vapoursynth-script
Description: Library for interfacing VapourSynth with Python
Version: 30

Requires: vapoursynth
Requires.private: python-3.5
Libs: -L${libdir} -lvapoursynth-script
Libs.private: -LC:/builds/ab/msys64/mingw64/lib -lpython3.5m
Cflags: -I${includedir}
```

**Comment by pat357** [comment]
Version 30 ?
I installed R29 2 days ago !!

**Comment by wiiaboo** [comment]
It's from git. Version doesn't matter.

**Comment by wiiaboo** [comment]
If you can't compile with vapoursynth-script (because it needs python) you can compile just with vapoursynth and use it via lua scripts.

**Comment by pat357** [comment]
I wonder about the lib names.
When I find for example "-lzimg" under libs or Libs.private, I expect the system searches for libzimg.a.
I  goes this way for all .pc files I checked.....

Is this not a kind of a rule that -lxyz expects a lib called libxyz ?

**Comment by wiiaboo** [comment]
It does in the case of .a libs. For .lib files it doesn't assume the file starts with lib.

**Comment by pat357** [comment]
I see, didn't know that...
Have you tried to parse a VS script (to sharp, denoise,...) via the Lua interface from MPV ?

**Comment by wiiaboo** [comment]
Nah. I don't need any filtering anyway.

**Comment by pat357** [comment]
Where do you use VS for than together with MPV ?

**Comment by wiiaboo** [comment]
I don't. That's why I've never been very interested in adding it.
FFmpeg's filters are good enough for most stuff.

**Comment by pat357** [comment]
but not for scaling, correct colors,...

**Comment by wiiaboo** [comment]
For playback mpv's opengl renderer has good quality. For encoding I don't really need anything but FFmpeg has zimg too now, so it's the same as vapoursynth.

**Comment by pat357** [comment]
How do you use ffmpeg to scale with zimg for example ?
The same question for tesseract, I can't get it work..

**Comment by wiiaboo** [comment]
https://ffmpeg.org/ffmpeg-filters.html#zscale
https://ffmpeg.org/ffmpeg-filters.html#ocr

Never used either. zscale is easy enough. ocr no idea.

**Comment by pat357** [comment]
Also, if you use something like MadVR as renderer, you can do some tuning (denoise, scale, .....) during playback. No need to too de processing before encoding stage.

**Comment by pat357** [comment]
to do the processing before the encoding stage.   ...

**Comment by wiiaboo** [comment]
opengl renderer is as good as madvr as far as i'm concerned.

Even just using vapoursynth-lazy, mpv doesn't seem to want to work. I don't care enough to fix it.
