### ISSUE TITLE
x265.exe version downgrade

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#292]
The suite just finished compiling everything some 
minutes ago - snapshot used was https://github.com/jb-alvarado/media-autobuild_suite/commit/4b1c62c
(more recent have been pushed already!).
No errors, all was fine.

When I went to copy compiled x265.exe to its proper 
location elsewhere on disk, I run:

`x265 --version` => 
`x265 [info]: HEVC encoder version 1.7-936-g8ace3c7`
`x265 [info]: build info [Windows][GCC 5.3.0][32 bit] 8bit+10bit+12bit`
`x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64 SlowShuffle`

and that struck me as odd, because my 
previously compiled x265.exe (on 28/02/2016) reports:

`x265 --version` => 
`x265 [info]: HEVC encoder version 1.9+39-45c0dbd43dec2460`
`x265 [info]: build info [Windows][GCC 5.3.0][32 bit] 8bit+10bit+12bit`
`x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64 SlowShuffle`

which suggests a version downgrade (1.9 => 1.7) currently by the script!
It appears that https://github.com/jb-alvarado/media-autobuild_suite/commit/4da028e, which was authored to fix the recent 
hg breakage by pushed MSYS2 updates, files a good candidacy 
for being responsible, though this is as far as I go; 
let the real expert handle it!

Regards

EDIT: it appears commit git-8ace3c7
https://github.com/videolan/x265/commit/8ace3c7
is the same as commit hg-0989743
https://bitbucket.org/multicoreware/x265/commits/0989743
with commit title:
**motion: set search method/subpel refine for each PU**
so it is indeed fresh code. 
And perhaps `1.7-936`, 936 revisions after tag 1.7, 
could well be tag 1.9+xx... but why the discrepancy? 
Tag 1.9 already exists in the github mirror: 
https://github.com/videolan/x265/releases/tag/1.9
... for the life of me, I'll never fully understand VCS!

**Comment by wiiaboo** [comment]
The commit is exactly the same. Just the right tag wasn't being used.

**Comment by Vangelis66** [comment]
Thanks a bunch @wiiaboo !

Recently compiled x265.exe now reports:

`x265 [info]: HEVC encoder version 1.9-53-g076d47a`
`x265 [info]: build info [Windows][GCC 5.3.0][32 bit] 8bit+10bit+12bit`
`x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64 SlowShuffle`

which is indeed great, however **one small issue still persists**:
When we would compile from bitbucket source, 
the revision number would be reflected 
upon file/product version, e,g. 1.9.0.39, see: 

![hg-compile](https://cloud.githubusercontent.com/assets/9669492/13500415/1b453a86-e16b-11e5-86fd-e63179d248b1.jpg)

whereas now that we compile from GitHub mirror, 
this is no longer the case; version shows up as 1.9.0.0:

![git-compile](https://cloud.githubusercontent.com/assets/9669492/13500474/623b4052-e16b-11e5-8105-cfb63d7fdd49.jpg)

Could something be done to restore things 
the way they were before, or have I driven you 
nuts already with my peculiarities? 

In any case, very grateful already!
Best regards.

**Comment by wiiaboo** [comment]
That's past my jurisdiction, I guess. Try asking in their issue tracker.

**Comment by wiiaboo** [comment]
Should look the same, other than different revision format, since git commits aren't the same as mercurial revision IDs.
![image](https://i.fsbn.eu/weKL.png)

**Comment by Vangelis66** [comment]
Let me just say first that I won't be persuing this 
any further with you (@wiiaboo), it isn't like I am paying you 
to constantly write code for me, you have already 
done enough and even more!

I must be suffering from OCD, but just for the record 
I'll voice two things I consider as inconsistencies: 

Yesterday's x265.exe compile would report: 
`x265 [info]: HEVC encoder version 1.9-53-g076d47a`
and file version 1.9.0.0
One can easily trace that it was built from commit 
git-**076d47a** from the GitHub mirror:
https://github.com/videolan/x265/commit/076d47a
which is identical to bitbucket commit hg-**9cc9920**
https://bitbucket.org/multicoreware/x265/commits/9cc9920
What I had wished for as an enhancement 
(and it was like that before) was the file version 
be reported as 1.9.0.53
(hg-**9cc9920** commit is currently the latest, 
pushed on 201603021156Z).

Having updated the suite to its latest snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/28589f3901da89b486cb2e76f1286efef2df470a, 
a short while ago the forced recompilation of x265.exe 
has finished; fresh binary now reports: `x265 -V` =>

`x265 [info]: HEVC encoder version1.9+53-g40ba1eb`

Mind you, it was built on the same code as 
yesterday's binary, no updates have occurred 
in between. However, the **g40ba1eb** string 
implies a git commit git-40ba1eb, which is nowhere 
to be found in the GitHub mirror repo! 
(and of course there is neither a hg-40ba1eb 
commit in bitbuckert repo...)
So now impossible to trace the source used.
Thankfully, file version is now reported as 1.9.0.53

But this brings me to a second possible inconsistency:
If you navigate to this site [videohelp](http://forum.videohelp.com/threads/357754-%5BHEVC%5D-x265-EXE-mingw-builds/page65?s=45e9c539177ec391f31f779c5eb4b564) and download 
@LigH-de's package (either mediafire link 
or attachment), that one reports: `x265_ml.exe -V` => 

`x265 [info]: HEVC encoder version 1.9+54-291beccb6760`
`x265 [info]: build info [Windows][GCC 5.3.0][32 bit] 8bit+10bit+12bit`

and file version **1.9.0.54**
That one was built from bitbucket source hg-**291becc**: 
https://bitbucket.org/multicoreware/x265/commits/291becc, 
that commit was pushed on 201602261053Z, many days 
before current HEAD, yet the file version is already onto 
1.9.0.54, while my most recent compile is still at 1.9.0.53, 
despite being built on the latest code. 
By comparing bitbucket vs GitHub I do see and 
understand same commits (identical code pushed) 
have different commit hashes in the two repos, 
but shouldn't the revision number be the same? 
(Or am I missing something fundamental?).

In any case, I've decided to stop nitpicking; 
only serious suite breakages from now on... 

> Or annoy Msys to stop breaking random stuff. 

I have a good mind to do so, so I went to https://msys2.github.io/
but was puzzled as to where to report hg breakage. Is it: 
https://github.com/alexpux/msys2-packages/issues or
https://github.com/alexpux/mingw-packages/issues
(or somewhere else?).
A quick browse of the two did not reveal anything 
hg related - yet: `$ hg clone https://bitbucket.org/multicoreware/x265`
in minnty yields: `abort: No such process!`
Such is life...

Most kind regards

**Comment by LigH-de** [comment]
> @LigH-de's package (either mediafire link
> or attachment), that one reports: `x265_ml.exe -V` =>
>
> `x265 [info]: HEVC encoder version 1.9+54-291beccb6760`
> `x265 [info]: build info [Windows][GCC 5.3.0][32 bit] 8bit+10bit+12bit`
>
> and file version **1.9.0.54**

I can only hope that I did not confuse my own source state. Sometimes I use the Mercurial Workbench in Windows, sometimes I update in MSYS using a script calling hg. I once noticed that a "merge with stable" commit jumped in the order. Might be best to freshly clone my sources and compare if they are still the same...

But Indeed I did make the experience that the hg repo on Bitbucket is not completely compatible to git; one should really use hg / Mercurial to process it.

**Comment by wiiaboo** [comment]
@Vangelis66 complain in MSYS-Packages. `import ssl` doesn't work in Python, so it probably needs to be recompiled in order for mercurial to work with HTTPS repositories.

The commit hash being wrong was a typo. It's fixed now.

**Comment by wiiaboo** [comment]
No need to report anything, they recompiled python already.

**Comment by wiiaboo** [comment]
Also, don't trust git to treat commits the same as mercurial. [Github shows there's been 92 commits since 1.9](https://github.com/videolan/x265/releases/tag/1.9), that's reproducible with `git rev-list --count`.
