### ISSUE TITLE
SClavc: can't load SceneChange-lavc.dll

### ISSUE THREAD

**Issue by unixfx** [jb-alvarado/media-autobuild_suite#443]
Hi 

This is my issue 
[https://postimg.org/image/oinxlnyrn/](url)

My system: Win 8.1 64bit

**Comment by unixfx** [comment]
I just Fixed it 

thanx =)

**Comment by wiiaboo** [comment]
Then close it, especially since I have no idea what this has to do with the suite.

**Comment by unixfx** [comment]
Ok I have another issue 
I tried to encode in  'yuv420p10le'  pixel format, but i got an error " Incompatible pixel format 'yuv420p10le' for codec 'libx264'"

**Comment by wiiaboo** [comment]
That's still not a problem with the suite. Ask in FFmpeg IRC or forums.
You probably didn't compile FFmpeg with 10-bit x264. It's either 8 or 10, can't have both.
